# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guest/Learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guest/Learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guest/Learning/CMakeFiles /home/guest/Learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guest/Learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named learning

# Build rule for target.
learning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 learning
.PHONY : learning

# fast build rule for target.
learning/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/build
.PHONY : learning/fast

Examples/Initialization.o: Examples/Initialization.cpp.o
.PHONY : Examples/Initialization.o

# target to build an object file
Examples/Initialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/Initialization.cpp.o
.PHONY : Examples/Initialization.cpp.o

Examples/Initialization.i: Examples/Initialization.cpp.i
.PHONY : Examples/Initialization.i

# target to preprocess a source file
Examples/Initialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/Initialization.cpp.i
.PHONY : Examples/Initialization.cpp.i

Examples/Initialization.s: Examples/Initialization.cpp.s
.PHONY : Examples/Initialization.s

# target to generate assembly for a file
Examples/Initialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/Initialization.cpp.s
.PHONY : Examples/Initialization.cpp.s

Examples/MoveSemantics.o: Examples/MoveSemantics.cpp.o
.PHONY : Examples/MoveSemantics.o

# target to build an object file
Examples/MoveSemantics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/MoveSemantics.cpp.o
.PHONY : Examples/MoveSemantics.cpp.o

Examples/MoveSemantics.i: Examples/MoveSemantics.cpp.i
.PHONY : Examples/MoveSemantics.i

# target to preprocess a source file
Examples/MoveSemantics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/MoveSemantics.cpp.i
.PHONY : Examples/MoveSemantics.cpp.i

Examples/MoveSemantics.s: Examples/MoveSemantics.cpp.s
.PHONY : Examples/MoveSemantics.s

# target to generate assembly for a file
Examples/MoveSemantics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Examples/MoveSemantics.cpp.s
.PHONY : Examples/MoveSemantics.cpp.s

FactoryPattern/General/ShapeCreator.o: FactoryPattern/General/ShapeCreator.cpp.o
.PHONY : FactoryPattern/General/ShapeCreator.o

# target to build an object file
FactoryPattern/General/ShapeCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/FactoryPattern/General/ShapeCreator.cpp.o
.PHONY : FactoryPattern/General/ShapeCreator.cpp.o

FactoryPattern/General/ShapeCreator.i: FactoryPattern/General/ShapeCreator.cpp.i
.PHONY : FactoryPattern/General/ShapeCreator.i

# target to preprocess a source file
FactoryPattern/General/ShapeCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/FactoryPattern/General/ShapeCreator.cpp.i
.PHONY : FactoryPattern/General/ShapeCreator.cpp.i

FactoryPattern/General/ShapeCreator.s: FactoryPattern/General/ShapeCreator.cpp.s
.PHONY : FactoryPattern/General/ShapeCreator.s

# target to generate assembly for a file
FactoryPattern/General/ShapeCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/FactoryPattern/General/ShapeCreator.cpp.s
.PHONY : FactoryPattern/General/ShapeCreator.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Main.cpp.s
.PHONY : Main.cpp.s

Threading/ThreadPool.o: Threading/ThreadPool.cpp.o
.PHONY : Threading/ThreadPool.o

# target to build an object file
Threading/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Threading/ThreadPool.cpp.o
.PHONY : Threading/ThreadPool.cpp.o

Threading/ThreadPool.i: Threading/ThreadPool.cpp.i
.PHONY : Threading/ThreadPool.i

# target to preprocess a source file
Threading/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Threading/ThreadPool.cpp.i
.PHONY : Threading/ThreadPool.cpp.i

Threading/ThreadPool.s: Threading/ThreadPool.cpp.s
.PHONY : Threading/ThreadPool.s

# target to generate assembly for a file
Threading/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/Threading/ThreadPool.cpp.s
.PHONY : Threading/ThreadPool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... learning"
	@echo "... Examples/Initialization.o"
	@echo "... Examples/Initialization.i"
	@echo "... Examples/Initialization.s"
	@echo "... Examples/MoveSemantics.o"
	@echo "... Examples/MoveSemantics.i"
	@echo "... Examples/MoveSemantics.s"
	@echo "... FactoryPattern/General/ShapeCreator.o"
	@echo "... FactoryPattern/General/ShapeCreator.i"
	@echo "... FactoryPattern/General/ShapeCreator.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Threading/ThreadPool.o"
	@echo "... Threading/ThreadPool.i"
	@echo "... Threading/ThreadPool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

